### ISSUE TITLE
Perl script for SNV density filtering?

### ISSUE THREAD

**Issue by cizydorczyk** [phac-nml/snvphyl-tools#10]
Hello,

I'm wondering if there happens to be a perl script/other tool for density filtering after running SNVPhyl with no density filter? I have searched the repo but could not find anything but thought I would ask before writing my own.

I ask because I wish to compare different density thresholds vs. other recombination-identification/masking tools, but would rather avoid re-running the entire SNVPhyl pipeline just to change density filters if I could. I run SNVPhyl using the SNVPhyl CLI rather than directly on a Galaxy instance.

Thank you!
Conrad Izydorczyk

**Comment by apetkau** [comment]
Hello @cizydorczyk. Unfortunately, there is no script we have available for SNV density filtering after SNVPhyl is run, though I imagine this could be done by scanning the **snvTable.tsv** file. In SNVPhyl the SNV density filtering is written as a plugin to `bcftools` (https://github.com/phac-nml/snvphyl-tools/blob/master/bcfplugins/filter_snv_density.c) and operates on the bcf files containing the identified SNVs (https://github.com/phac-nml/snvphyl-tools/blob/master/bin/consolidate_vcfs.pl#L165).

**Comment by cizydorczyk** [comment]
Thank you for the clarification -- much appreciated! I will see what I can do with scanning the snvTable.tsv file.
